# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=75)),
                ('nombre_interno', models.CharField(max_length=75)),
                ('fecha_estreno', models.DateField()),
                ('genero', models.CharField(max_length=150)),
                ('sinopsis', models.CharField(max_length=1000)),
                ('cartel', models.ImageField(upload_to='images')),
                ('enlace', models.URLField()),
                ('actores', models.ManyToManyField(to='cine.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='Proyeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('aforo_max', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='proyeccion',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Sala'),
        ),
    ]
